spring:
    profiles:
        active: dev   #环境配置

mybatis:
    mapper-locations: mapper/**/*Mapper.xml
    type-aliases-package: model.boot_mybatis.model.*


#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql